export enum InputTypes {
  'BUTTON' = 'button',
  'CHECKBOX' = 'checkbox',
  'COLOR' = 'color',
  'DATE' = 'date',
  'DATETIME_LOCAL' = 'datetime-local',
  'EMAIL' = 'email',
  'FILE' = 'file',
  'HIDDEN' = 'hidden',
  'IMAGE' = 'image',
  'MONTH' = 'month',
  'NUMBER' = 'number',
  'PASSWORD' = 'password',
  'RADIO' = 'radio',
  'RANGE' = 'range',
  'RESET' = 'reset',
  'SEARCH' = 'search',
  'SUBMIT' = 'submit',
  'TEL' = 'tel',
  'TIME' = 'time',
  'URL' = 'url',
  'WEEK' = 'week',
  'TEXT' = 'text',
  'TEXTAREA' = 'textarea',
}

export enum InputAutoCompleteTypes {
  'ON' = 'on',
  'OFF' = 'off',
  'NAME' = 'name',
  'HONORIFIC_PREFIX' = 'honorific-prefix',
  'GIVEN_NAME' = 'given-name',
  'ADDITIONAL_NAME' = 'additional-name',
  'FAMEILY_NAME' = 'family-name',
  'HONORIFIC_SUFFIX' = 'honorific-suffix',
  'NICKNAME' = 'nickname',
  'EMAIL' = 'email',
  'USERNAME' = 'username',
  'NEW_PASSWORD' = 'new-password',
  'CUREENT_PASSWORD' = 'current-password',
  'ORGANIZATION_TITLE' = 'organization-title',
  'ORGANIZATION' = 'organization',
  'URL' = 'url',
  'SEX' = 'sex',
  'BIRTHDAY' = 'birthday',
  'BIRTHDAY_YEAR' = 'bday-year',
  'BIRTHDAY_MONTH' = 'bday-month',
  'BIRTHDAY_DAY' = 'bday-day',
  'COUNTRY' = 'country',
  'POSTAL_CODE' = 'postal-code',
  'COUNTRY_NAME' = 'country-name',
}
