export enum SpinnerSize {
  'small' = 'small',
  'default' = 'default',
  '2x' = '2x',
  '3x' = '3x'
}

export enum SpinnerColor {
  'dark' = 'dark',
  'normal' = 'normal',
  'custom' = 'custom'
}

export enum SpinnerType {
  'ball-beat' = 'ball-beat',
  'pacman' = 'pacman',
  'ball-8bits' = 'ball-8bits',
  'ball-atom' = 'ball-atom',
  'ball-circus' = 'ball-circus',
  'ball-climbing-dot' = 'ball-climbing-dot',
  'ball-clip-rotate' = 'ball-clip-rotate',
  'ball-clip-rotate-multiple' = 'ball-clip-rotate-multiple',
  'ball-clip-rotate-pulse' = 'ball-clip-rotate-pulse',
  'ball-elastic-dots' = 'ball-elastic-dots',
  'ball-fall' = 'ball-fall',
  'ball-fussion' = 'ball-fussion',
  'ball-grid-beat' = 'ball-grid-beat',
  'ball-grid-pulse' = 'ball-grid-pulse',
  'ball-newton-cradle' = 'ball-newton-cradle',
  'ball-pulse' = 'ball-pulse',
  'ball-pulse-rise' = 'ball-pulse-rise',
  'ball-pulse-sync' = 'ball-pulse-sync',
  'ball-rotate' = 'ball-rotate',
  'ball-running-dots' = 'ball-running-dots',
  'ball-scale' = 'ball-scale',
  'ball-scale-multiple' = 'ball-scale-multiple',
  'ball-scale-pulse' = 'ball-scale-pulse',
  'ball-scale-ripple' = 'ball-scale-ripple',
  'ball-scale-ripple-multiple' = 'ball-scale-ripple-multiple',
  'ball-spin' = 'ball-spin',
  'ball-spin-clockwise' = 'ball-spin-clockwise',
  'ball-spin-clockwise-fade' = 'ball-spin-clockwise-fade',
  'ball-spin-clockwise-fade-rotating' = 'ball-spin-clockwise-fade-rotating',
  'ball-spin-fade' = 'ball-spin-fade',
  'ball-spin-fade-rotating' = 'ball-spin-fade-rotating',
  'ball-spin-rotate' = 'ball-spin-rotate',
  'ball-square-clockwise-spin' = 'ball-square-clockwise-spin',
  'ball-square-spin' = 'ball-square-spin',
  'ball-triangle-path' = 'ball-triangle-path',
  'ball-zig-zag' = 'ball-zig-zag',
  'ball-zig-zag-deflect' = 'ball-zig-zag-deflect',
  'cog' = 'cog',
  'cube-transition' = 'cube-transition',
  'fire' = 'fire',
  'line-scale' = 'line-scale',
  'line-scale-party' = 'line-scale-party',
  'line-scale-pulse-out' = 'line-scale-pulse-out',
  'line-scale-pulse-out-rapid' = 'line-scale-pulse-out-rapid',
  'line-spin-clockwise-fade' = 'line-spin-clockwise-fade',
  'line-spin-clockwise-fade-rotating' = 'line-spin-clockwise-fade-rotating',
  'line-spin-fade' = 'line-spin-fade',
  'line-spin-fade-rotating' = 'line-spin-fade-rotating',
  'square-jelly-box' = 'square-jelly-box',
  'square-loader' = 'square-loader',
  'square-spin' = 'square-spin',
  'timer' = 'timer',
  'triangle-skew-spin' = 'triangle-skew-spin'
}
