export enum GameType {
  'PRE_SEASON' = 'PR',
  'REGULAR_SEASON' = 'R',
  'PLAYOFFS' = 'P',
  'ALL_STARS' = 'A',
  'ALL_STARS_WOMEN_GAMES' = 'WA',
  'OLYMPIC_GAME' = 'O',
  'WORLD_CUP_EXIBITION' = 'WCOH_EXH',
  'WORLD_CUP_PRLIMINARY' = 'WCOH_PRELIM',
  'WORLD_CUP_FINALS' = 'WCOH_FINAL',
}
