export enum GoalieStatsEnum {
  'evenSaves' = 'evenSaves',
  'evenShots' = 'evenShots',
  'evenStrengthSavePercentage' = 'evenStrengthSavePercentage',
  'games' = 'games',
  'gamesStarted' = 'gamesStarted',
  'goalAgainstAverage' = 'goalAgainstAverage',
  'goalsAgainst' = 'goalsAgainst',
  'losses' = 'losses',
  'ot' = 'ot',
  'powerPlaySavePercentage' = 'powerPlaySavePercentage',
  'powerPlaySaves' = 'powerPlaySaves',
  'powerPlayShots' = 'powerPlayShots',
  'savePercentage' = 'savePercentage',
  'saves' = 'saves',
  'shortHandedSavePercentage' = 'shortHandedSavePercentage',
  'shortHandedSaves' = 'shortHandedSaves',
  'shortHandedShots' = 'shortHandedShots',
  'shotsAgainst' = 'shotsAgainst',
  'shutouts' = 'shutouts',
  'ties' = 'ties',
  'timeOnIce' = 'timeOnIce',
  'timeOnIcePerGame' = 'timeOnIcePerGame',
  'wins' = 'wins',
}

export enum SkaterStatsEnum {
  'assists' = 'assists',
  'blocked' = 'blocked',
  'evenTimeOnIce' = 'evenTimeOnIce',
  'evenTimeOnIcePerGame' = 'evenTimeOnIcePerGame',
  'faceOffPct' = 'faceOffPct',
  'gameWinningGoals' = 'gameWinningGoals',
  'games' = 'games',
  'goals' = 'goals',
  'hits' = 'hits',
  'overTimeGoals' = 'overTimeGoals',
  'penaltyMinutes' = 'penaltyMinutes',
  'pim' = 'pim',
  'plusMinus' = 'plusMinus',
  'points' = 'points',
  'powerPlayGoals' = 'powerPlayGoals',
  'powerPlayPoints' = 'powerPlayPoints',
  'powerPlayTimeOnIce' = 'powerPlayTimeOnIce',
  'powerPlayTimeOnIcePerGame' = 'powerPlayTimeOnIcePerGame',
  'shifts' = 'shifts',
  'shortHandedGoals' = 'shortHandedGoals',
  'shortHandedPoints' = 'shortHandedPoints',
  'shortHandedTimeOnIce' = 'shortHandedTimeOnIce',
  'shortHandedTimeOnIcePerGame' = 'shortHandedTimeOnIcePerGame',
  'shotPct' = 'shotPct',
  'shots' = 'shots',
  'timeOnIce' = 'timeOnIce',
  'timeOnIcePerGame' = 'timeOnIcePerGame',
}
